"use strict";
exports.__esModule = true;
var Groestl_1 = require("./Groestl");
var gr224 = new Groestl_1["default"](224);
console.log('Groestl 224');
console.log("abc\n", gr224.hash("abc"));
console.log("abc.\n", gr224.hash("abc."));
console.log('====');
var gr256 = new Groestl_1["default"](256);
console.log('Groestl 256');
console.log("\"The quick brown fox jumps over the lazy dog\"\n", gr256.hash("The quick brown fox jumps over the lazy dog"));
console.log("\"The quick brown fox jumps over the lazy dog.\"\n", gr256.hash("The quick brown fox jumps over the lazy dog."));
console.log('====');
var gr384 = new Groestl_1["default"](384);
console.log('Groestl 384');
console.log("\"The quick brown fox jumps over the lazy dog\"\n", gr384.hash("The quick brown fox jumps over the lazy dog"));
console.log("\"The quick brown fox jumps over the lazy dog.\"\n", gr384.hash("The quick brown fox jumps over the lazy dog."));
console.log('====');
var gr512 = new Groestl_1["default"](512);
console.log('Groestl 512');
console.log("\"The quick brown fox jumps over the lazy dog\"\n", gr512.hash("The quick brown fox jumps over the lazy dog"));
console.log("The quick brown fox jumps over the lazy dog.\n", gr512.hash("The quick brown fox jumps over the lazy dog."));
